### ISSUE TITLE
Moved Examples.

### ISSUE THREAD

**Issue by Justinfront** [Justinfront/hxDaedalus#26]
I have moved the examples to a separate repository.
https://github.com/Justinfront/hxDaedalus-Examples
I have only moved hxml files we need to add openfl/hxproj files back, I just did not fire up PC yet.
Not sure about putting #if everywhere, but maybe we can factor them out as we converge sources at lower levels. Maybe we can move to adding some excludes in examples but if we get examples working first.
There was a problem rendering js on my browsers so I have modified the js lineStyle commands (that seemed to be dart)?
I have added a Haxelib.json field it would be nice to get hxDaedalus on Haxelib for Christmas and then look to adding examples a bit later.  Will aim to get bitmap stuff working very soon for js but maybe we can put hxDaedalus on there tomorrow?

**Comment by Justinfront** [comment]
Azrafe7 
I need to work out how to get the #if right for the OpenFL html5 bitmapPathfinding example, and need to exclude a lot of the bin code ( be nice to maybe keep a debug.apk a swf and html5 ) demo.  I am not quite sure there is a way to host bitmapPathfinding example using github raw unless maybe I put the encoded image into the html and grab it from there? As security stops me parsing the pixels if the image is external?  Have you had a chance to look yet at the code changes. Hoping your could consider the Pixel class some more my hack round was a bit ugly but was think maybe your class had more functionality than was strictly needed in this project as I only had to implement a bit for js to get code working.  I guess I made a lot of changes I am not sure if all of them where good.  It would be nice to get these repositories ok to add them to haxelib for the haxe blog announcements tomorrow?
Best Justin

**Comment by Justinfront** [comment]
Ok fixed it for openfl html5 stuff should all work now correctly.

**Comment by Justinfront** [comment]
Had to remove all contributors but me to allow upload of haxelib till other users register with haxelib.

**Comment by azrafe7** [comment]
Sorry for being away for so long (unexpected things got in the way). But hey, congrats for the release on haxelib!

I'll be operative by wednesday night/thursday, so if you can tell me what should I look into first I'll b glad to start working on it.

**Comment by Justinfront** [comment]
Hay Azrafe7, yer sorry about releasing it without you checking over stuff but I guessed you were tied up and we had a good slot on the haxe blog, just after christmas is always a good time, and the screenshot was the header for the post so I think the lib got good publicity, and Skial was keen for us to send details of future updates.  In terms of things that need improving.

The big one at the moment is Openfl Android - the bitmap examples don't seem to run on blue stack simulator properly, black where transparency is not yet tried hooking up a device but should work same as blue stack simulator also I think it was slow. Really would like to know that openfl iphone is running. And other phones firefox os and windows8 with js and Tizen with openfl, but testing some maybe hard.

The openfl example needs the maze added, but that's not very interesting but should be added soon, I ment to add in but, in trying to get videos together etc... I missed it out, also git needs to change to limit bin files, it would be nice to have an apk swf html to download and jar but as you said a lot of the other files should be removed.

Talk to joshua more on using create to install examples automagically with haxelib.json without examples being in haxelib.

I have not checked what needs for latest NME, what tweaks on Openfl project are needed for nice NME use maybe with less bloat NME might be better in another repository.

The new canvas html stuff I probably did not integrate really well, just got it to work, and we need to do testing cross browser and I know that the way I did it was not ideal but did not get round to adjusting it, but should not be doing calculations every call so needs tidying improving.

Not sure if it's too early to try implementing Neko Cairo, probably Neko Cairo is hard to setup but not hard to implement as Cairo seem similar to canvas, but I am quite happy to take a look next time I put weekend time in, but maybe wait till Neko Cairo is more finished project.

It terms of new demos, I am keen to make the maze away3d haxe.

Other demo's we need moving blocks example. And maybe look at how blocks and bitmaps can be combined... maybe bitmap ghosts in maze ( packman ).

Looking briefly at Cedric.Flash repository there is more docs now with info probably more stuff that we should demo, stuff we don't even know is possible.

But at moment I am most interested in how we might mix this with polygonal's pathfinding code, and also how we can join maps to make multilevels.

So I guess there is plenty.  If you prefer to just tidy up and look at some other ports, I am thinking it might be good to port an OCR js lib I saw will have to re google it sometime, but not sure licence is ideal.  But I can imagine it would be nice to have a bitmap working that locations are automatically detected and added as listed destinations and haxe needs some ocr.

Then flambe we should try to sort.

Java we need to add slick2d

Current code base could be set to a single style but there is always risk of breaking stuff and code seems to work well so not really concerned about that right now.

Well just a few ideas :)

Best Justin

**Comment by Justinfront** [comment]
oh the hxml examples I am still not compleatly sure on this approach and some are not totally merged, I think it is good though for users to see how you can code like this if your not used to true power of haxe.

**Comment by azrafe7** [comment]
I've tested the GridMaze demo on my Android (2.3) device and it works fine (with both openfl and nme).
I should mention that I'm using slightly outdated versions of the libs:

 - openfl 2.1.5
 - nme 5.1.8

**Comment by Justinfront** [comment]
That's good news.

I think it is bitmap stuff where transparent is black so already guessed - it would be less likely to effect the maze maybe it's a png issue that Joshua will be fixing soon or we could try to submit a pull fix or something.  I noticed you were using older openfl in your pull, I think ideally we should try to use the most recent haxelib.  I tried to go with flashdevelop templates as much as possible partially because I don't use openfl much - often troublesome on mac, my prefered tool, so was not quite sure on the reasons for some of the changes, I think I am on a recent FD so templates should be new, but happy to go with you decisions on the openfl repository, just it's ideal if code starts out like a normal template project and will feel more accessible, but I did not look closely but maybe a pull with latest haxelibs would be better?

**Comment by azrafe7** [comment]
If my recent NME/OpenFL-related PR is okay for you (ensuring it's working fine on mac), I mean to propose another one featuring the built executables for flash/android/html.

I'm still having some issues related to CrossOrigin, and I hope you can take a look at that to solve it.

**Comment by Justinfront** [comment]
The problem is security on the image because of different domains, i think.

**Comment by azrafe7** [comment]
Yes, but I thought rawgit copied the filed over to its own domain and
served them from there...
I guess I'm wrong with this assumption, but really don't know how to fix it.

2015-01-18 19:38 GMT+01:00 Justinfront <notifications@github.com>:

**Comment by Justinfront** [comment]
well I think I got an error when it tries to read the pixels from memory.  Maybe we can embed images in the code or in the html. I can't rem the details but maybe if the image is in the html as an src we can grab it by the class https://github.com/Justinfront/divtastic3/blob/master/src/core/DisplayDiv.hx#L374

**Comment by azrafe7** [comment]
It sounds like your idea should work! Another thing worth considering would
be the use of macros, but that also would not make the code any easier to
read.

I remember stumbling upon a topic on reddit (quite some time ago!), that
did exactly what I thought rawgit was doing: i.e. cloning the repo on its
own domain and serving html/js from there, but I cannot find it anymore.

Maybe we should just drop this _automated_ thing and host the compiled
examples somewhere?!

2015-01-18 19:46 GMT+01:00 Justinfront <notifications@github.com>:

**Comment by Justinfront** [comment]
Replacing the path with the base64 encode gif string seems to work well, it's a bit messy accessing it because I have to split on slashes, but without loader it does not work online, fixed a render issue and updated the hxDaedalus-Examples, I have updated the main hxDaedalus readme with image, blog link and the new example.
![](https://rawgit.com/Justinfront/hxDaedalus-Examples/master/hxDaedalus-Examples/web/DaedalusBitmapPathfinding.html)

**Comment by Justinfront** [comment]
We should add images above the demos I guess, using exclaimation mark followed by empty square brackets, then currly brackets to raw path with question mark raw = true.
